# Base Image for mycobot 280
FROM nvidia_ros:latest
SHELL ["/bin/bash", "-c"]

# Install basic apt packages
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  git \
  gnupg gnupg1 gnupg2 \
  libcanberra-gtk* \
  python3-catkin-tools \
  python3-pip \
  python3-tk \
  wget

# Install mycobot dependency
RUN pip3 install pymycobot  

# Create Catkin workspace with mycobot_ros package
RUN mkdir -p /mycobot_ws/src \
 && cd /mycobot_ws/src \
 && source /opt/ros/noetic/setup.bash \
 && catkin_init_workspace \
 && git clone https://github.com/elephantrobotics/mycobot_ros.git

# Build the base Catkin workspace
RUN cd /mycobot_ws \
 && source /opt/ros/noetic/setup.bash \
 && rosdep install -y --from-paths src --ignore-src \
 && catkin build 

# Remove display warnings
RUN mkdir /tmp/runtime-root
ENV XDG_RUNTIME_DIR "/tmp/runtime-root"
ENV NO_AT_BRIDGE 1

# Set up the work directory and entrypoint
WORKDIR /mycobot_ws
COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
